name:
  maximum: 50
email:
  maximum: 255
password:
  minimum: 6
gavatar:
  size: 80
  micropost_size: 50
remember_me: "1"
password_reset_expired: 2
micropost:
  maximum: 140
picture_size: 5
picture_accept: "image/jpeg,image/gif,image/png"
